### ISSUE TITLE
Investigate differences between PIN and Aero Messages

### ISSUE THREAD

**Issue by 0xlsca** [themeldingwars/PIN#18]
The following removed classes need to be searched for named fields which are unknown in `AeroMessages`.

- `UdpHosts/GameServer/Packets/GSS/Character/BaseController/MovementInput.cs` (removed in #[7d5c351](https://github.com/themeldingwars/PIN/pull/16/commits/7d5c351f5703e74b65770a39714cf1fc0f81753e))
- `UdpHosts/GameServer/Packets/GSS/Generic/ScheduleUpdateRequest.cs` (removed in #[7d5c351](https://github.com/themeldingwars/PIN/pull/16/commits/7d5c351f5703e74b65770a39714cf1fc0f81753e))

**Comment by eXpl0it3r** [comment]
It should be okay to move everything to Aero, as Aero is the golden source for the packets. All the other information was sourced from other places and is less precise/complete.  
But of course there might be some additional code changes required that we can document.

**Comment by 0xlsca** [comment]
Tbh, my motivation originates from the transition to `ConfirmedPoseUpdate` in `Character/BaseController.MovementInput where I spotted that Aero doesn't include a field we have a name for.

`ConfirmedPoseUpdate` in Aero:

```cs
    [Aero]
    [AeroMessageId(MsgType.GSS, MsgSrc.Message, 2, 111)]
    public partial class ConfirmedPoseUpdate
    {
        public MovementPoseData PoseData;
        public ushort Unk; <-- This field
    }
```
`ConfirmedPoseUpdate` in PIN:
```cs
    [GSSMessage(Enums.GSS.Controllers.Character_BaseController, (byte)Events.ConfirmedPoseUpdate)]
    public class ConfirmedPoseUpdate
    {
        [Field]
        public ushort ShortTime;

        [Field]
        public byte UnkByte1;

        [Field]
        public byte UnkByte2;

        [Field]
        public Vector Position;

        [Field]
        public Quaternion Rotation;

        [Field]
        public ushort State;

        [Field]
        public Vector Velocity;

        [Field]
        public ushort UnkUShort1;

        [Field]
        public ushort UnkUShort2;

        [Field]
        public ushort LastJumpTimer;

        [Field]
        public byte UnkByte3;

        [Field]
        public ushort NextShortTime; <-- This field
```

Additionally, just tracking the removed files and when they were removed seems suitable because we can proceed with removing obsolete code and don't need to scan all of them at once.

**Comment by Xsear** [comment]
> Tbh, my motivation originates from the transition to `ConfirmedPoseUpdate` in `Character/BaseController.MovementInput` where I spotted that Aero doesn't include a field we have a name for.
> 
> `ConfirmedPoseUpdate` in Aero:
> 
> ```cs
>     [Aero]
>     [AeroMessageId(MsgType.GSS, MsgSrc.Message, 2, 111)]
>     public partial class ConfirmedPoseUpdate
>     {
>         public MovementPoseData PoseData;
>         public ushort Unk; <-- This field
>     }
> ```
> 
> `ConfirmedPoseUpdate` in PIN:
> 
> ```cs
>     [GSSMessage(Enums.GSS.Controllers.Character_BaseController, (byte)Events.ConfirmedPoseUpdate)]
>     public class ConfirmedPoseUpdate
>     {
>         [Field]
>         public ushort ShortTime;
> 
>         [Field]
>         public byte UnkByte1;
> 
>         [Field]
>         public byte UnkByte2;
> 
>         [Field]
>         public Vector Position;
> 
>         [Field]
>         public Quaternion Rotation;
> 
>         [Field]
>         public ushort State;
> 
>         [Field]
>         public Vector Velocity;
> 
>         [Field]
>         public ushort UnkUShort1;
> 
>         [Field]
>         public ushort UnkUShort2;
> 
>         [Field]
>         public ushort LastJumpTimer;
> 
>         [Field]
>         public byte UnkByte3;
> 
>         [Field]
>         public ushort NextShortTime; <-- This field
> ```
> 
> Additionally, just tracking the removed files and when they were removed seems suitable because we can proceed with removing obsolete code and don't need to scan all of them at once.

Thanks for pointing it out, just wanted to note here, I have since updated this in AeroMessages: https://github.com/themeldingwars/AeroMessages/commit/3febce7f1fe01f3826eaefc78d65ae3c808f58f9

**Comment by eXpl0it3r** [comment]
Switch has been done with #30
