### ISSUE TITLE
Incoming split packages

### ISSUE THREAD

**Issue by zSleepwalker** [themeldingwars/PIN#35]
Seems the GameServer doesn't support incoming split packages. just sending them.
This was first experienced when BagInventorySettings sent information.

**Comment by eXpl0it3r** [comment]
https://github.com/themeldingwars/PIN/blob/aa775cd888128a4031951270f3c0ee17cff1c8dd/UdpHosts/GameServer/Channel.cs#L139

**Comment by Xsear** [comment]
Supported since some time ago: https://github.com/themeldingwars/PIN/blob/acbd027e5afb53e66eed01440f16a1c387677973/UdpHosts/GameServer/Channel.cs#L108-L135
