### ISSUE TITLE
Implementation of CI

### ISSUE THREAD

**Issue by ben132** [themeldingwars/PIN#54]
This would be useful for testing, I know that it would be potentially unnecessary given the scale of the current userbase, but it may improve the chances of someone stumbling onto it to giving it a try and testing it, and then as a result get invested.  And on a personal note I can never get builds to work on git project, but that is just me.

**Comment by eXpl0it3r** [comment]
We already have CI builds. I assume what you mean is to publish the artefacts.

It's something that should be done.

**Comment by eXpl0it3r** [comment]
I've enabled the step again. Once the builds are through, you can find the latest master branch version here (requires a GitHub account): https://github.com/themeldingwars/PIN/actions/runs/12049691457
