### ISSUE TITLE
unable to get operator settings, client will be unable to connect.

### ISSUE THREAD

**Issue by terrawillow** [themeldingwars/PIN#9]
![gib troubleshoot pls](https://user-images.githubusercontent.com/68619229/137651276-7ed902dc-9c5c-4896-9814-04dbf4ed996f.png)
![ploxx](https://user-images.githubusercontent.com/68619229/137651346-8c5cba71-ef45-4df1-895a-2ae7780e920b.png)

First, I downloaded firefall from steam. Then, I located the firefall.ini inside of steamapps\common\Firefall and replaced the content with 
"[Config]
OperatorHost = "localhost:4400"

[FilePaths]
AssetStreamPath = "http://localhost:4401/AssetStream/%ENVMNEMONIC%-%BUILDNUM%/"
VTRemotePath = "http://localhost:4401/vtex/%ENVMNEMONIC%-%BUILDNUM%/static.vtex"

[UI]
PlayIntroMovie = false"
I downloaded the latest PIN release and made a backup of my original firefallclient.exe in firefall\system\bin
I installed the newest .net 5 runtime
After this I attempted to trust the self-signed development certs by running "dotnet dev-certs https --trust" in the command console, but it told me that the correct version hadn't been installed. I worked past that thinking it might not be an issue.
I started GameServer and MatrixServer, but WebHostManager wouldn't start. I figured it had something to do with the certs. The version of .net 5 I initially installed was 5.0.11. I downgraded to 5.0.0 hoping it would help, but it didn't. Eventually, I installed the sdk as well, and that got WebHostManager running. 
I booted up firefall, and despite the .ini's instructions the intro scene played. Logging in didn't work, no matter what I put in the field.

**Comment by terrawillow** [comment]
Output of GameServer:
"[17:27:30 INF] Listening on 0.0.0.0:25001"
Output of MatrixServer:
"[17:27:29 INF] Listening on 0.0.0.0:25000"
Output of WebHostManager (in Gitbash):
$ ./webhostmanager.exe
Hosting environment: Production
Content root path: H:\Program Files\Steam\steamapps\common\Firefall\PirateIntelligenceNetwork
Now listening on: https://localhost:44307
Now listening on: http://localhost:4407
Application started. Press Ctrl+C to shut down.
Hosting environment: Production
Content root path: H:\Program Files\Steam\steamapps\common\Firefall\PirateIntelligenceNetwork
Now listening on: https://localhost:44302
Now listening on: http://localhost:4402
Application started. Press Ctrl+C to shut down.
Hosting environment: Production
Content root path: H:\Program Files\Steam\steamapps\common\Firefall\PirateIntelligenceNetwork
Now listening on: https://localhost:44300
Now listening on: http://localhost:4400
Application started. Press Ctrl+C to shut down.
Hosting environment: Production
Content root path: H:\Program Files\Steam\steamapps\common\Firefall\PirateIntelligenceNetwork
Now listening on: https://localhost:44303
Now listening on: http://localhost:4403
Application started. Press Ctrl+C to shut down.
Hosting environment: Production
Content root path: H:\Program Files\Steam\steamapps\common\Firefall\PirateIntelligenceNetwork
Now listening on: https://localhost:44306
Now listening on: http://localhost:4406
Application started. Press Ctrl+C to shut down.
Hosting environment: Production
Content root path: H:\Program Files\Steam\steamapps\common\Firefall\PirateIntelligenceNetwork
Now listening on: https://localhost:44308
Now listening on: http://localhost:4408
Application started. Press Ctrl+C to shut down.
Hosting environment: Production
Content root path: H:\Program Files\Steam\steamapps\common\Firefall\PirateIntelligenceNetwork
Now listening on: https://localhost:44310
Now listening on: http://localhost:4410
Application started. Press Ctrl+C to shut down.
Hosting environment: Production
Content root path: H:\Program Files\Steam\steamapps\common\Firefall\PirateIntelligenceNetwork
Now listening on: https://localhost:44301
Now listening on: http://localhost:4401
Application started. Press Ctrl+C to shut down.

**Comment by eXpl0it3r** [comment]
This usually happens if you haven't installed the dev certificate with `dotnet dev-certs https --trust`.

Let me know if this fixed it for you

**Comment by 0xlsca** [comment]
Heya @terrawillow !
Is this issue still present on your end?
